---
- name: Prairie single-node Rancher deployment
  hosts: cattle
  become: true
  gather_facts: true

  vars:
  # Pick the kubeconfig path based on distro, defaulting to k3s only if nothing else sets it
    prairie_kubeconfig_path: "{{ '/etc/rancher/k3s/k3s.yaml'
                                  if (prairie_kubernetes_distribution | default('k3s')) == 'k3s'
                                  else '/etc/rancher/rke2/rke2.yaml' }}"

  environment:
    KUBECONFIG: "{{ prairie_kubeconfig_path }}"

  roles:
    - base
    - role: k3s
      when: prairie_kubernetes_distribution == 'k3s'
    - role: rke2
      when: prairie_kubernetes_distribution == 'rke2'
    - rancher
    - { role: longhorn, when: storage_engine == 'longhorn' }

