---
- name: Prairie single-node Rancher deployment
  hosts: cattle
  become: true
  gather_facts: true

  vars:
    # Default Kubernetes distro; can be overridden in inventory or via --extra-vars
    prairie_kubernetes_distribution: "k3s"

    # Pick the kubeconfig path based on distro
    prairie_kubeconfig_path: "{{ '/etc/rancher/k3s/k3s.yaml' if prairie_kubernetes_distribution == 'k3s' else '/etc/rancher/rke2/rke2.yaml' }}"

  environment:
    KUBECONFIG: "{{ prairie_kubeconfig_path }}"

  roles:
    - base

    - role: k3s
      when: prairie_kubernetes_distribution == 'k3s'

    - role: rke2
      when: prairie_kubernetes_distribution == 'rke2'

    - rancher
